### ISSUE TITLE
postgresql drop schema

### ISSUE THREAD

**Issue by navi86** [terraform-providers/terraform-provider-postgresql#101]
Hi there,
I am trying to destroy postgresql resource when schema contains depended resources.

terraform version v0.12.6

### Affected Resource(s)
Please list the resources as a list, for example:
- postgresql_schema

### Expected Behavior
Resource "postgresql_schema" has option "cascade" for deleting depended resources.

### Actual Behavior
Operation failed due to the fact that schema has depended resources. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform destroy when schema has depended resources`

**Comment by cyrilgdn** [comment]
Hi @navi86 ,

Thanks for opening this issue.

Yes I think we can implement a `DROP CASCADE` option but it should probably be disabled by default (as it's very dangerous operation :) )

**Comment by jtownson** [comment]
Adding my vote.
This feature would support the following very common use-case:
* terraform creates initial schema
* flyway creates tables and app runs for a time
* terraform destroys schema (including the tables).
Currently this scenario does not work. The drop schema fails because there are tables referencing that schema.

**Comment by cyrilgdn** [comment]
I created a PR for that #108 , reviews are welcomed !

**Comment by navi86** [comment]
@cyrilgdn,
big thanks for your work

**Comment by cyrilgdn** [comment]
FYI, this feature has been released  in [v1.4.0](https://github.com/terraform-providers/terraform-provider-postgresql/releases/tag/v1.4.0) 2 days ago :+1:
