### ISSUE TITLE
Authentication failure with Aurora PostgreSQL

### ISSUE THREAD

**Issue by leahneukirchen** [terraform-providers/terraform-provider-postgresql#106]
### Terraform Version

```
% terraform -v
Terraform v0.12.18
+ provider.postgresql v1.3.0
```

### Affected Resource(s)

- provider "postgresql"

### Terraform Configuration Files
```hcl
provider "postgresql" {
  alias = "rds"
  host            = "127.0.0.1"
  port            = 5432
  username        = "postgres"
  password        = "mysecretpassword"
  sslmode         = "require"
  connect_timeout = 15
  superuser       = false
}

resource "postgresql_database" "db" {
  provider = postgresql
  name = "foo"
}
```

### Debug Output

```
2019-12-16T11:29:21.408+0100 [INFO]  plugin: configuring client automatic mTLS
2019-12-16T11:29:21.436+0100 [DEBUG] plugin: starting plugin: path=/home/leah/work/tf-bug/.terraform/plugins/linux_amd64/terraform-provider-postgresql_v1.3.0_x4 args=[/home/leah/work/tf-bug/.terraform/plugins/linux_amd64/terraform-provider-postgresql_v1.3.0_x4]
2019-12-16T11:29:21.437+0100 [DEBUG] plugin: plugin started: path=/home/leah/work/tf-bug/.terraform/plugins/linux_amd64/terraform-provider-postgresql_v1.3.0_x4 pid=10304
2019-12-16T11:29:21.437+0100 [DEBUG] plugin: waiting for RPC address: path=/home/leah/work/tf-bug/.terraform/plugins/linux_amd64/terraform-provider-postgresql_v1.3.0_x4
2019-12-16T11:29:21.444+0100 [INFO]  plugin.terraform-provider-postgresql_v1.3.0_x4: configuring server automatic mTLS: timestamp=2019-12-16T11:29:21.444+0100
2019-12-16T11:29:21.476+0100 [DEBUG] plugin.terraform-provider-postgresql_v1.3.0_x4: plugin address: network=unix address=/tmp/plugin216437641 timestamp=2019-12-16T11:29:21.476+0100
2019-12-16T11:29:21.476+0100 [DEBUG] plugin: using plugin: version=5
2019-12-16T11:29:21.541+0100 [DEBUG] plugin.terraform-provider-postgresql_v1.3.0_x4: 2019/12/16 11:29:21 [INFO] PostgreSQL DSN: `host='' port=5432 dbname=postgres user=postgres password=<redacted> sslmode='' connect_timeout=180 fallback_application_name='Terraform provider'`
2019/12/16 11:29:21 [ERROR] <root>: eval: *terraform.EvalConfigProvider, err: Error initializing PostgreSQL client: error detecting capabilities: error PostgreSQL version: pq: password authentication failed for user "postgres"
2019/12/16 11:29:21 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error initializing PostgreSQL client: error detecting capabilities: error PostgreSQL version: pq: password authentication failed for user "postgres"
2019/12/16 11:29:21 [ERROR] <root>: eval: *terraform.EvalOpFilter, err: Error initializing PostgreSQL client: error detecting capabilities: error PostgreSQL version: pq: password authentication failed for user "postgres"
2019/12/16 11:29:21 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error initializing PostgreSQL client: error detecting capabilities: error PostgreSQL version: pq: password authentication failed for user "postgres"
```

### Expected Behavior

Terraform should connect to the DB server and plan to create the database.

### Actual Behavior

```
Error: Error initializing PostgreSQL client: error detecting capabilities: error PostgreSQL version: pq: password authentication failed for user "postgres"

  on <empty> line 0:
  (source code not available)
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The server is a SSH-forwarded Aurora PostgreSQL:

```
postgres=> SELECT VERSION();
                                   version                                   
-----------------------------------------------------------------------------
 PostgreSQL 10.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.9.3, 64-bit
(1 row)
```

Connecting with `psql -h localhost -U postgres` and the password **works**.

Setting `$PGPASSWORD` to the password **works too**, so somehow passing the password from the TF config is broken.

(We use the same plugin against non-Aurora PostgreSQL and it works fine.)

**Comment by leahneukirchen** [comment]
This seems to be due to the `alias =`, which probably doesn't make it the default provider even if there is only one provider... if this is by intention, then WONTFIX.

**Comment by elliottyates** [comment]
I'm seeing something similar to this with terraform 0.12.8 and provider.postgresql 1.2.0 or 1.3.0. I use AWS RDS as the backend. Terraform apply works fine; terraform import fails with the message reported by @leahneukirchen. Perhaps, if this is deemed something that won't be fixed, it could be helpful to give more information about how to debug the issue (i.e. if it's a user/client config issue, instead of a terraform issue)?

**Comment by cyrilgdn** [comment]
@leahneukirchen Indeed, you need to specify ``provider = "postgresql.rds"`` if you set this alias on your provider. You have no default provider defined in your example.

@elliottyates For import Terraform does not currently read the provider from the configuration so you need to specify which provider to use to import your resource.
If I take @leahneukirchen resource as example, you'll need to do:
```
terraform import -provider postgresql.rds postgresql_database.db foo
```
See also: https://github.com/hashicorp/terraform/issues/17139

Terraform does not currently read from the configur

**Comment by elliottyates** [comment]
Thank you @cyrilgdn and @leahneukirchen.

**Comment by elliottyates** [comment]
@cyrilgdn, would you actually be able to give further details? My situation is that I'm trying to import something in a module unrelated to my (module-scoped) postgresql provider, but it fails each time, telling me I have an authentication or version error (I find the wording a bit unclear):

```
Error: Error initializing PostgreSQL client: error detecting capabilities: error PostgreSQL version: pq: password authentication failed for user "X"
```

(where user X is the correct name I give to the `provider` block in that db-specific module)

The provider is non-aliased, but declared inside a module. Adding `-provider postgresql` doesn't resolve the issue, and in fact shows an additional error:

```
Error: Error initializing PostgreSQL client: error detecting capabilities: error PostgreSQL version: dial tcp :5432: connect: connection refused

  on <empty> line 0:
  (source code not available)
```

I'm trying to figure out how to either (a) ignore the postgresql provider configuration for the purposes of importing the other resource(s), or (b) provide terraform what it needs to resolve this provider issue. Any suggestions? Thanks, and sorry to comment on a closed ticket. Happy to open a new one if this is a different problem than the OP's.

**Comment by cyrilgdn** [comment]
@elliottyates Not sure to get what you're trying to do :thinking: 

Could you create a new issue with, if possible, a (non) working example ? 
(I prefer not discuss too much in a closed PR as I may forgot it if I can't answer directly :sweat_smile: )

**Comment by elliottyates** [comment]
Thanks @cyrilgdn -- apologize for the delay, and for continuing the thread in a closed issue. The next time I bump into this I'll try to do a better job of isolating it! I'm not great at debugging tf internals, go, or getting all that's going on here; wish I could do a better job explaining. Next time I'll dig in more, and open a new ticket if I can. Cheers.

**Comment by dishbreak** [comment]
As an aside, you'll also get this failure if you're providing the password via dynamic confing. In my case, I was using `aws_kms_secrets` as a data source to retrieve the password. In order to import I had to paste in the plaintext password. My guess is that this is because Terraform doesn't do a full round of interpolation as part of the import process.
