### ISSUE TITLE
existing role kills database seeding

### ISSUE THREAD

**Issue by ausfestivus** [terraform-providers/terraform-provider-postgresql#107]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
11.14

### Affected Resource(s)
- `postgresql_role`

### Terraform Configuration Files
```hcl
resource "postgresql_role" "tfe-role" {
  name               = "${lower(var.PREFIX)}_role_admin"
  login              = true
  password           = "REDACTED"
  encrypted_password = true
}
```

### Debug Output
2019-12-18T04:25:39.5761886Z 	* postgresql_role.tfe-role: error creating role tfenterprisedev_role_admin: pq: role "tfenterprisedev_role_admin" already exists

### Panic Output
`nil`

### Expected Behavior
An info should be logged that it exists.
An attempt should be made to use the role.
If the attempt fails, then die, else carry on with the apply.

### Actual Behavior
The apply failed.

### Steps to Reproduce
Database Layer:
1. create a postgres instance in Azure.

App Layer:
1. create your infra and app stack using TF
2. use the postgresql provider to seed the database you created in the database layer above
3. deploy app. Success.

time passes

1. new deploy of app stack, destroys old stack
2. app stack tries to seed the database again with the role and extensions
3. witness error about role already existing
4. app stack cannot deploy unless we delete the role in the database layer.

### Important Factoids
Sure, you could create the role in the database layer stack, except there is https://github.com/terraform-providers/terraform-provider-postgresql/issues/2 which is gathering dust.

Dont say null resources and local-exec.

### References
https://github.com/terraform-providers/terraform-provider-postgresql/issues/2

**Comment by cyrilgdn** [comment]
Hi @ausfestivus , thanks for opening this issue,

I have some questions because I'm not sure to get everything.

* What's the link between #2 and the fact you can't create the role with Terraform? (BTW there's now a little workaround for #2, see my last comment inside it)
* When and by who the role is actually created?

**Comment by ausfestivus** [comment]
Morning @cyrilgdn 

* The link with #2 is that I would like to take the role creation out of the app stack TF and do it in the TF for the database layer. #2 (now worked around) lets me move the DB and role creation TF back into the DB layer TF.
* The role was being created in the app layer TF because of #2. The app layer TF is idempotent so in development/testing I would regularly destroy the app layer and recreate/redeploy it. Because the role already existed in the DB (created by the previous app layer TF run) subsequent app layer runs would fail.

Im going to move the role definition stuff to the DB layer now because that is the more correct way to handle this. I only had the role creation the app layer to work around #2
