### ISSUE TITLE
Allow Specification of PostgreSQL Instance/Connection as Resource

### ISSUE THREAD

**Issue by romeara** [terraform-providers/terraform-provider-postgresql#109]
### Terraform Version

The problem/obstacle this seeks to address has been reproduced as of Terraform 0.12.12

### Problem

I have attempting to create a Terraform setup that both creates/provisions a PostgreSQL instance, and then applies setup (such as creating a database and roles) to that instance. During these attempts, I have run into the problem described in many areas, including Terraform issue [2430](https://github.com/hashicorp/terraform/issues/2430) - because the connection to PostgreSQL is configured as part of the provider, and the instance I want to connect to is itself setup by Terraform (via a separate provider) the setup fails during the first `plan` execution, because the instance to connect to doesn't (yet) exist.

### Requested Enhancement/Feature

My request is to consider whether it would be appropriate to change how the PostgreSQL provider setup occurs, such that the "PostgreSQL Instance/Connection", rather than being associated with the provider, be defined as a resource (which is then referenced by the other existing resources). In this way, it could be treated as having dependencies (such as the setup step that creates it) and better integrate with a larger variety of use-cases for end-to-end setup of PostgreSQL infrastructure.

So, for example, this setup (with an assumed AWS-provided database setup called `aws_db_instance.myDB`):

```
provider "postgresql" {
   host = "${aws_db_instance.myDB.address}"
   port = "${aws_db_instance.myDB.port}"
   username = "${aws_db_instance.myDB.username}"
   password = "abc"
 }
```

becomes something like this:

```
provider "postgresql" {
}

resource "postgresql_connection" "aws_postgres" {
   host = "${aws_db_instance.myDB.address}"
   port = "${aws_db_instance.myDB.port}"
   username = "${aws_db_instance.myDB.username}"
   password = "abc"
 }
```

with the implied `depends_on` to the `aws_db_instance.myDB` resource

**Comment by cyrilgdn** [comment]
Hi @romeara ,

Thanks for opening this issue. I allow myself to close it as it seems to be linked to #2 .

There's now a workaround for this problem as you can read in [my comment](https://github.com/terraform-providers/terraform-provider-postgresql/issues/2#issuecomment-567887609) in the aforementioned PR. You can specify the [`expected_version`](https://www.terraform.io/docs/providers/postgresql/index.html#expected_version) attribute in the provider configuration to avoid it to connect to the database during `terraform plan`.

**Comment by romeara** [comment]
Oh, I didn't realize that the connection was just to find the version - that helps, thank you! I'm not sure if that will resolve such issues during the apply step, however - I will try that workaround and report back. (`plan` was simply the first step I could not get past to even try `apply`, so I am unsure as to its behavior)

Thanks for the quick reply/guidance!

**Comment by cyrilgdn** [comment]
@romeara Should work with apply too. I tested it (but with a simple configuration) and was able to create RDS instance and Postgres database in the same `apply`.

`apply` actually starts by a `plan`, then when the Postgresql resource is really applied, the RDS instance is already created (with proper dependency between both of course).

Let me know if it's not the case!

**Comment by romeara** [comment]
Appears to be working with apply as well - now I'm just debugging connection issues, but terraform is at least attempting the connection at what seems to be the correct step in the sequence.

Thanks!
