### ISSUE TITLE
looks like a bug  in postgresql_grant

### ISSUE THREAD

**Issue by bharathnoddy** [terraform-providers/terraform-provider-postgresql#116]
Hi there,
  I want to create a readonly user in AWS postgres RDS  and here is the code for that
```
resource "postgresql_role" "reader_role" {
  name = user_reader
  login = true
  password = somepasssss
  skip_reassign_owned = true
}

resource postgresql_grant "readonly_tables" {
  database    = DB_name
  role        =    user_reader
  schema      = "public"
  object_type = "table"
  privileges  = ["SELECT"]
}
```

It works fine it created the user and grants the permission on table , but it does not grants USAGE permission on the schema because of which the user cannot see any table.

Is this some bug or I am doing something wrong ?

I am using tf version 0.12.18

**Comment by cyrilgdn** [comment]
Hi @bharathnoddy ,

You need to specify the permissions for the schema too.
For now, permissions for schema have to be declare in the [`postgresql_schema` resource](https://www.terraform.io/docs/providers/postgresql/r/postgresql_schema.html) (with the policy block):

e.g.:
```
resource "postgresql_schema" "my_schema" {
  name  = "my_schema"
  owner = "postgres"

  policy {
    usage = true
    role  = "role_name"
  }
}
```
We plan to make it possible via the `postgresql_grant` resource too.

I close this issue but feel free to open it back if I didn't totally answer to your question.
