### ISSUE TITLE
Unable to set max_connections to zero

### ISSUE THREAD

**Issue by andyyaldoo** [terraform-providers/terraform-provider-postgresql#125]
### Terraform Version
```sh
$ terraform -v
Terraform v0.12.20
```

### Affected Resource(s)
- provider.postgresql

### Terraform Configuration Files
```hcl
provider "postgresql" {
  host            = "postgres_server_ip"
  port            = 5432
  database        = "postgres"
  username        = "postgres_user"
  password        = "postgres_password"
  sslmode         = "require"
  connect_timeout = 15
  max_connections = 0
}
```

### Expected Behavior

Based on the documentation [here](https://www.terraform.io/docs/providers/postgresql/index.html#max_connections), it says that setting the `max_connections` to 0 will, set the maximum connections for the db to unlimited.

### Actual Behavior
Plan shows error:
```
Error: max_connections can not be less than 1
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### References
- #81 

If the intention is to prevent user from setting the max_connections to unlimited, maybe we should amend the documentation or provide another safe alternative

**Comment by cyrilgdn** [comment]
Hi @andyyaldoo ,

Thank you for reporting this.

> If the intention is to prevent user from setting the max_connections to unlimited

Not at all, I'll change the validation of this field to allow 0

**Comment by cyrilgdn** [comment]
@andyyaldoo I created the PR #128 for that, if you have a bit of time to quickly review it so I can merge it, it would be helpful.
Thanks a lot.

**Comment by andyyaldoo** [comment]
done
