### ISSUE TITLE
Can we add cascade = true/false in postgresql_extension?

### ISSUE THREAD

**Issue by andyyaldoo** [terraform-providers/terraform-provider-postgresql#137]
### Terraform Version
```
❯ terraform -v
Terraform v0.12.20
+ provider.postgresql v1.2.0

Your version of Terraform is out of date! The latest version
is 0.12.24. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)
Please list the resources as a list, for example:
- postgresql_extension

### Terraform Configuration Files
```hcl
resource "postgresql_extension" "this" {
   name = "aws_s3"
   cascade = true # or false
}
```

**Comment by cyrilgdn** [comment]
Hi @andyyaldoo ,

Thanks for opening this issue,

I think we can yes and, unless if I miss something, this should not be a big modification so we'll try to do if for the next release.

We'll let you know here when we'll work on it.
