### ISSUE TITLE
v1.6.0 release

### ISSUE THREAD

**Issue by stack72** [terraform-providers/terraform-provider-postgresql#138]
Hi

Please can v1.6.0 of the provider be released? It would be great to be able to get the provider working with the clientcerts

Thanks

paul

**Comment by cyrilgdn** [comment]
Hi,

Yes sorry for the delay, I wanted to integrate an important patch in this release but didn't take enough time to work on it...

I will prepare and ask for a release by the end of the week, so at the latest v1.6.0 will be released next Monday.

I'll keep you posted here when it's released.

**Comment by cyrilgdn** [comment]
Hi,

Version 1.6.0 has been released last Friday.

**Comment by stack72** [comment]
Thanks so much!
