### ISSUE TITLE
PostgreSQL provider is not using lazy connections

### ISSUE THREAD

**Issue by estahn** [terraform-providers/terraform-provider-postgresql#140]
### Terraform Version
```
Terraform v0.12.24
+ provider.aws v2.36.0
+ provider.kubernetes v1.10.0
+ provider.mysql v1.9.0
+ provider.postgresql v1.6.0
+ provider.rabbitmq v1.3.0
+ provider.random v2.2.1
```

### Affected Resource(s)
- provider.postgres

### Terraform Configuration Files
```hcl
provider "postgresql" {
  version  = "~> 1.6"
  alias    = "foo"
  host     = aws_db_instance.foo.address
  username = var.foo_username
  password = var.foo_password
  connect_timeout = 10
  superuser = false
}
```

### Debug Output
```
aws_db_parameter_group.custom-notmidship: Importing from ID "custom-notmidship"...
aws_db_parameter_group.custom-notmidship: Import prepared!
  Prepared aws_db_parameter_group for import
aws_db_parameter_group.custom-notmidship: Refreshing state... [id=custom-notmidship]
Error: Error initializing PostgreSQL client: error detecting capabilities: error PostgreSQL version: dial tcp 172.31.31.5:5432: connect: operation timed out
  on /myproject/providers.tf line 89, in provider "postgresql":
  89: provider "postgresql" {
```

### Expected Behavior
Running an import action (or any action for that matter) which is not touching posgres resources should not trigger the initialisation of the postgres provider.

Example:
```
 terraform import aws_db_parameter_group.custom-notmidship custom-notmidship
```

### Actual Behavior
The postgres provider tries to connect to the database. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Define postgres provider, see above
2. Run ` terraform import ...`

**Comment by mced** [comment]
@cyrilgdn Do you have any news on this or a workaround except commenting postgresql providers when importing a resource ?
