### ISSUE TITLE
v1.7.0 Error: pq: column "prokind" does not exist

### ISSUE THREAD

**Issue by blkt** [terraform-providers/terraform-provider-postgresql#159]
### Terraform Version
Terraform v0.12.28
Postgres 10.12 (both dockerized and on AWS RDS)

### Affected Resource(s)
- `postgresql_grant`

### Terraform Configuration Files
```hcl
terraform {
  required_version = "= 0.12.28"
}

locals {
  pg_host = "127.0.0.1"
  pg_port = 5432
}

provider "postgresql" {
  alias = "this"

  host     = local.pg_host
  port     = local.pg_port
  database = "postgres"

  version = "~> 1.7"
}

provider "random" {
  version = "2.2.1"
}

resource "postgresql_database" "db" {
  name             = "foo"
  template         = "template1"
  lc_collate       = "en_US.utf8"
  lc_ctype         = "en_US.utf8"
}

resource "postgresql_role" "rw_username" {
  name                = "bar"
  login               = true
  password            = "quux"
  inherit             = false
  skip_reassign_owned = true # AWS RDS compatibility
}

resource "postgresql_default_privileges" "rw_default_privileges_functions" {
  database    = postgresql_database.db.name
  role        = postgresql_role.rw_username.name
  schema      = "public"
  owner       = "postgres"
  object_type = "function"
  privileges = [
    "EXECUTE",
  ]
}

resource "postgresql_grant" "rw_privileges_functions" {
  database    = postgresql_database.db.name
  role        = postgresql_role.rw_username.name
  schema      = "public"
  object_type = "function"
  privileges = [
    "EXECUTE"
  ]
}
```

### Debug Output
https://gist.github.com/blkt/38f2cb834a00490b97ffde8ac636097b

### Panic Output
The error did not result in a panic.

### Expected Behavior
Something like the following
```
foo=# GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO bar;
GRANT
```

### Actual Behavior
Error due to missing column.

### Steps to Reproduce
Against a local Postgres (e.g. docker):
1. `TF_LOG=DEBUG PGSSLMODE=disable terraform apply`

### Important Factoids
Nothing worth mentioning.

### References
No open issues searching for "prokind"

**Comment by blkt** [comment]
Hello, any news on this regard? Were there other issues related to this bug that you've been working on?

**Comment by Tommi2Day** [comment]
will take a look for alternatives

**Comment by spko** [comment]
Hi, @Tommi2Day !
Thank you for the quick fix on this issue, would you when you would release it or when the next release would happen?

Cheers :)

**Comment by Tommi2Day** [comment]
I am only one of the contributers. A new release will be done by @cyrilgdn

**Comment by cyrilgdn** [comment]
Yes, sorry for the delay, I've been off for a while. I'll take a look as soon as possible.

**Comment by spko** [comment]
Thank you both for the update guys!

Looking forward to using the new version 👍
