### ISSUE TITLE
Updating a role password doesn't actually update the role password

### ISSUE THREAD

**Issue by tomelliff** [terraform-providers/terraform-provider-postgresql#16]
When updating a role password a plan shows a change:
```
~ postgresql_role.app
    password: "<sensitive>" => "<sensitive>" (attribute changed)
```
but after applying the change it doesn't actually appear to have been changed.

Taking a quick look at the source code I don't see anything for updating the role password so I guess it just hasn't been implemented yet?

### Terraform Version
Terraform v0.9.11

### Terraform Configuration Files
```hcl
resource "postgresql_role" "app" {
  name     = "app"
  login    = true
  password = "my_password"
}
```

### Expected Behavior
The role password should be changed or at the least an error saying you can't change the role password.

### Actual Behavior
Nothing.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Change the password to something else
3. `terraform apply`
4. Try to login with new password and see it fail
5. Login with old password and it succeeds

**Comment by vascop** [comment]
Related to this issue, all passwords are reported as changing after importing, even if they're the same as the existing ones. After applying, they get reported as changed although nothing changed. Makes for a fun moment when importing live production databases.

**Comment by sean-** [comment]
Internally the PostgreSQL provider needs to emulate the password SHA and store the value.  This has been on my list of things to get around to but I haven't had a chance to work on this in a few months.  I'm hoping sometime in February I'll be able to get back to some of this and flesh out a few more resources.

**Comment by ahartma1** [comment]
Any update on this? I find that no matter whether im setting the password initially or changing it, neither works
