### ISSUE TITLE
sslmode simply doesn't work

### ISSUE THREAD

**Issue by sgendler-stem** [terraform-providers/terraform-provider-postgresql#24]
I can connect from the commandline psql client with ?sslmode=verify-full in the connect URL and it most definitely checks the certificate.  If I remove it from my local box, psql will fail to connect. If I reinstall it, it succeeds.  

```
psql (9.6.3, server 9.6.5)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

stem_prod=> 
```

When I specify ?sslmode=disable it definitely does not connect over SSL

```
psql (9.6.3, server 9.6.5)
Type "help" for help.

stem_prod=> 
```

However, no matter what value I put in sslmode in the provider declaration, including 'disable', it always errors out with the message 

```
* postgresql_role.minimal: 1 error(s) occurred:

* postgresql_role.minimal: Error creating role minimal: pq: SSL is not enabled on the server
```

Every resource that uses the postgresql provider reports the same error.  There are no further clues as to what exactly is failing.  I have verified that all of the values being passed to the provider are correct.  Is it possible that the pg library being used by the provider is somehow bypassing my VPN client?  The hostname definitely resolves to an address that is only reachable via VPN, but that entire network is set up to route through the VPN client. The commandline psql client certainly has no difficulty with it, nor does telnet.

**Comment by sgendler-stem** [comment]
It is looking as though variable interpolation of the outputs of a module in the same template as the postgresql provider doesn't work.  When I enable debug logging, I can see that it is connecting to host '' with defaults in port, username, and password.  I'm in the process of pulling the provider out into another template, which imports the state of the previous one, to see if variable interpolation works there.  If not, the provider is basically useless to me, since I first provision the db instance via other terraform providers before finally connecting to it - which seems like a pretty common use-pattern.  At the very least, a far more meaningful error message would be appropriate - something that maybe spits out the URL (with password obfuscated) that it attempted to connect with when it failed to connect.

**Comment by sgendler-stem** [comment]
Wow, all I can say is this provider (and terraform in-general) really needs better error handling.  It turns out that the postgresql resources all REQUIRE the provider attribute, which names a declared provider by alias, otherwise, they don't default to the single declared postgresql provider in the template, they default to an invisible postgresql provider which has default username, password, port, and empty host.  Then it errors out with a complaint about SSL not being enabled (because I've got some default postgres install on my local machine, which is what the empty host and default port number resolve to).  No mention of the host it is going to in the error message.  No mention of the missing provider attribute in the resource.  No mention of a default provider being used. I just had to figure it out by pure guesswork.  Even with the trace logs enabled, I was basically left clueless, except that I could see that it was using the wrong host, username, etc.  But there was no indication where they came from.  

I lost the better part of an entire day to something that could have been avoided with a couple lines of documentation or some reasonable error handling in the application.  Meanwhile, I could have written a script to just create the roles and extensions I need via psql, which also would have been able to creates roles as members of groups, in about 5 minutes.  Terraform ends up costing me huge quantities of time, compared to doing things manually, WAY too often. It's really a shame.  Frankly, if I knew then what I know now, I suspect I'd have skipped terraform entirely.  I am just constantly spending hours or days working around bugs or missing documentation - mostly the former.

**Comment by sean-** [comment]
@sgendler-stem I'm sorry to hear that.  Can you provide a sample terraform config that demonstrates this so I can understand better what's going on?  I confess, I'm not sure I fully understand because I think things are working correctly, but want to address your frustration because I'm sure you're not the only one who has bumped into this.

**Comment by sgendler-stem** [comment]
I would close this.  It was some cascade of bugs that were creating the impression of the 'bug' described here but I cannot even remember, offhand, what the actual issue turned out to be or how I worked around it.  It was definitely not as described above, however, so I'm closing this
