### ISSUE TITLE
Possible for new release?

### ISSUE THREAD

**Issue by 0xCMP** [terraform-providers/terraform-provider-postgresql#25]
I was trying to use this provider to setup a postgresql-9.4 server and it failed to create the user because of the RL feature not being blocked. 

I see that the changes were applied in July 2017 where the latest release was Jun 21, 2017. For now I'll have to build and manage my own release on my computer, but could we simply get a new release tagged and published? I ran the tests and it seems to work and probably suitable for a new release?

**Comment by sean-** [comment]
As soon as #26 and #27 go in, a release should go out.

**Comment by sean-** [comment]
#26 and #27 were merged, so we're g2g for a release, which should be getting cut sometime today.  I'm proactively closing this out, but expect `0.1.1` to be released later today.  Thank you for the nag to get this out the door and @catsby for shepherding the release.
