### ISSUE TITLE
Doesn't support Postgres 10

### ISSUE THREAD

**Issue by tomelliff** [terraform-providers/terraform-provider-postgresql#30]
The provider doesn't seem to support Postgres 10, failing with `Error initializing PostgreSQL client: error detecting capabilities: error parsing version: No Major.Minor.Patch elements found`

Postgres has moved to just Major.Minor version for the 10+ release, not Major.Minor.Patch.

Both acceptance tests and planning the following config with `docker run --name postgres -e POSTGRES_PASSWORD=mysecretpassword -d -p 5432:5432 --rm postgres:9.6` works fine, but they fail with `docker run --name postgres -e POSTGRES_PASSWORD=mysecretpassword -d -p 5432:5432 --rm postgres:10`

### Terraform Configuration Files
```hcl
provider "postgresql" {
  version = "~>0.1"

  host            = "localhost"
  port            = "5432"
  username        = "postgres"
  password        = "mysecretpassword"
  connect_timeout = 15
  sslmode         = "disable"
}

resource "postgresql_database" "database" {
  name  = "version-migration-test"
}

```
### Expected Behavior
Applies without an error

### Actual Behavior
Fails with `Error initializing PostgreSQL client: error detecting capabilities: error parsing version: No Major.Minor.Patch elements found`

### Steps to Reproduce
1. `terraform apply`

or run the acceptance tests pointing to the local Docker container.

I haven't looked too deeply into it but it looks like lib/pg supports Postgres 10 as they have Travis CI tests running for it but I didn't see a pull request fixing it if it's being thrown from there.

**Comment by tomelliff** [comment]
Looks like it's an issue in `blang/semver` as it expects 3 parts and raises an error if not.

**Comment by rsheldon** [comment]
I commented on the PR, but realized that it may be better to do so here. Can we please get a release with this fix in it released? Or at least a ETA?

**Comment by sean-** [comment]
@rsheldon I'm going to have some cycles to play with TF + PG over the next week and after I burn through a few items there I was going to see about getting a release kicked. Maybe in 1-2 weeks?

**Comment by rsheldon** [comment]
Thanks Sean. Look forward to trying it out.

**Comment by ctrom** [comment]
I seem to still be experiencing this:
`Error: provider.postgresql.cf_rds: invalid version ("10.3"): No Major.Minor.Patch elements found`

Provider version:
`provider.postgresql v0.1.2`

**Comment by ctrom** [comment]
I have found that if I specify the `expected_version` as `10.3.0` instead of `10.3`, that I can successfully connect to the postgres instance with this provider. `10.3.0` is not a valid postgres version (as noted by @tomelliff) so this is more of a hack than a solution, but it has unblocked me for now.

@sean- could you reopen this issue?

**Comment by joye-ramone** [comment]
I still see message: 
**error detecting capabilities: error parsing version: Invalid character(s) found in minor number "5,"**
select version(); return:
**"PostgreSQL 10.5, compiled by Visual C++ build 1800, 64-bit"**

Is it something that I can skip via configuration?

**Comment by tetlika** [comment]
still seeing error :+1: 
Error: Error refreshing state: 1 error(s) occurred:

* provider.postgresql: Error initializing PostgreSQL client: error detecting capabilities: error parsing version: Invalid character(s) found in minor number "5,"


I specified 

expected_version = "10.5.0"

**Comment by CumpsD** [comment]
Same problem when using an Azure Postgresql, also `10.5,`

**Comment by basyar02** [comment]
Still seeing the error : 
Error: invalid version ("10.7"): No Major.Minor.Patch elements found

 version         = "~> 1.1.0"
 expected_version = "10.7"

any feedback?

**Comment by cyrilgdn** [comment]
@basyar02 What's the result of ```SELECT version();``` query on your RDS instance ?

**Comment by basyar02** [comment]
> @basyar02 What's the result of `SELECT version();` query on your RDS instance ?
This : 

PostgreSQL 10.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.9.3, 64-bit

**Comment by cyrilgdn** [comment]
@basyar02 Actually it's your `expected_version` value (`10.7`) which does not have the good format.
The version is parsed by [semver.Parse](https://godoc.org/github.com/blang/semver#Parse) which expects a patch number too.
You can set:
```
expected_version = "10.7.0"
```

**Comment by tomelliff** [comment]
Except my linked PR switched to `ParseTolerant` a long time ago so that shouldn't be an issue now.

**Comment by basyar02** [comment]
> @basyar02 Actually it's your `expected_version` value (`10.7`) which does not have the good format.
> The version is parsed by [semver.Parse](https://godoc.org/github.com/blang/semver#Parse) which expects a patch number too.
> You can set:
> 
> ```
> expected_version = "10.7.0"
> ```

I have tested using the "10.7.0" and it still error :
"
Error: Error initializing PostgreSQL client: error detecting capabilities: error PostgreSQL version:..."

**Comment by basyar02** [comment]
Any update on this?

**Comment by adharmawan** [comment]
Faced this issue today, I deleted the `.terraform` folder and re-run terraform init. After I did that, somehow I no longer face this issue
