### ISSUE TITLE
Being a squeaky wheel to get a new version released

### ISSUE THREAD

**Issue by LucidNeko** [terraform-providers/terraform-provider-postgresql#41]
Hi there,

I headed over to https://www.terraform.io/community.html first and asked on gitter, the advice was to go and be a squeaky wheel over here :)

I'm waiting on a release containing 1ebb1d55bdb9d04ad8cff8f077df4d1ca5037d15 so that I can upgrade to terraform 11 and use postgres10 (currently hanging back on terraform 9 for that project, but using terraform 11 everywhere else)

Just getting an expected release timeline would be awesome.

Thanks for the great work on an amazing tool.

**Comment by sean-** [comment]
0.1.2 was released yesterday.  Enjoy.
