### ISSUE TITLE
Azure managed PostgreSQL service username mapping

### ISSUE THREAD

**Issue by lentferj** [terraform-providers/terraform-provider-postgresql#55]
**Terraform v0.11.10
provider.azurerm v.1.19.0
provider.postgresql  master c766a68**

The Azure managed PostgreSQL service seems to use pg_ident.conf or similar for user name mappings. When accessing a managed PostgreSQL service in Azure you need to specify  _username_@_servicename_, e.g. psqladmin@psqlserver1 in the connection string for the user.
Internally in PostgreSQL only the role _username_ exists (without the @_servicename_).
The initial user provided by the Azure managed PostgreSQL service also is not a superuser.

Now, if you try to e.g. create a database like this:

provider "postgresql" {
  host            = "some_service.postgres.database.azure.com"
  port            = 5432
  username        = "admin_test@some_service"
  password        = "${var.admintest_password}"
  sslmode         = "require"
  connect_timeout = 15
}

resource "postgresql_database" "my_db" {
  provider          = "postgresql" 
  name              = "my_db"
}

you will run into errors, because the code here

https://github.com/terraform-providers/terraform-provider-postgresql/blob/master/postgresql/resource_postgresql_database.go#L109

will use _username_@_servicename_ for GRANTs and so forth in e.g. grantRoleMembership, setDBOwner. This will end in ERRORs thrown by PostgreSQL, because the _username_@_servicename_ is not known (only _username_) is.

**Comment by peterbev** [comment]
As I only need this to work for Azure I took a hammer to the problem and replaced all instances of `c.config.Username` with `strings.Split(c.config.Username, "@")[0]` in resource_postgresql_database.go and resource_postgresql_role.go

Not terribly elegant but gets me past the stumbling block...

**Comment by cyrilgdn** [comment]
@lentferj  @peterbev I guess we can add a `DatabaseUsername` field in the provider config which will be empty by default (so equal to `Username`).

It will be more generic because `username@servicename` is Azure specific and [user name maps](https://www.postgresql.org/docs/9.1/auth-username-maps.html) can contain anything.

Does it seem ok for you?

**Comment by peterbev** [comment]
@cyrilgdn sounds good to me...

**Comment by cyrilgdn** [comment]
I created a little PR (#58) to manage this case. Feel free to review it :)
