### ISSUE TITLE
Temporarily add role membership when managing permissions

### ISSUE THREAD

**Issue by zytek** [terraform-providers/terraform-provider-postgresql#70]
Add `GRANT $owner TO $connected_user` when managing permissions.

Notice: we should probably remove this grant afterward to not leak permissions BUT only if it wasn't granted before we did it/checked for it. So, as far as I understand, provider should check if this membership is added, add it if not and later remove it.  

Mentioned in #53 
Related https://github.com/hashicorp/terraform/pull/11452

> when using this on RDS:
> 
> ```
> resource "postgresql_default_privileges" "priv-sequence-for-user" {
>   database    = "${var.db}"
>   owner       = "${var.owner}"
>   role        = "${var.user}"
>   schema      = "public"
>   object_type = "sequence"
>   privileges  = ["ALL"]
>   depends_on  = ["postgresql_database.db"]
> }
> ```
> we need to first run `GRANT ${var.owner} to ${provider.username}"
>

**Comment by zytek** [comment]
If anyone has this in progress please mention me, if not I will try to submit PR this week

**Comment by cyrilgdn** [comment]
@zytek Thanks, for opening the issue.

> Notice: we should probably remove this grant afterward to not leak permissions BUT only if it wasn't granted before we did it/checked for it. So, as far as I understand, provider should check if this membership is added, add it if not and later remove it.

True ! And if you give it a try, note that I already had to do something similar here: https://github.com/terraform-providers/terraform-provider-postgresql/blob/master/postgresql/resource_postgresql_database.go#L132-L142
So helpers already exist for that. (Unfortunately I added them after creating the PR for grant & default privileges :) )
