### ISSUE TITLE
When 0.2.2 would be released?

### ISSUE THREAD

**Issue by goruha** [terraform-providers/terraform-provider-postgresql#73]
Hello

When 0.2.2 would be released? 
We really need grant resource.

**Comment by cyrilgdn** [comment]
@goruha Thanks for raising this issue.

I was hoping to merge a last PR before releasing a new version but as it's longer than expected I'll ask for a new release today or tomorrow. (BTW  it will be the v0.3.0 :) ).

**Comment by kostya2011** [comment]
+1 for release :)

**Comment by cyrilgdn** [comment]
@goruha  @kostya2011 [v0.3.0](https://github.com/terraform-providers/terraform-provider-postgresql/releases/tag/v0.3.0) has just been released.
