### ISSUE TITLE
select data provider?

### ISSUE THREAD

**Issue by sixcorners** [terraform-providers/terraform-provider-postgresql#84]
Would it be a good idea to create a data provider that can return the results of a select statement?

**Comment by sixcorners** [comment]
Maybe something like this?
```hcl
data "postgresql_query_results" "tables" {
  query = "select table_name from information_schema.tables"
}

output "tables" {
  value = "${data.postgresql_select_statement.tables.results}"
}
```
I'm not sure about the nouns though.. query_results? query?  results?
Should it be something like result_sets? /shrug

**Comment by cyrilgdn** [comment]
Hi @sixcorners ,

What would be your use case for that?

We need to think about this but I already see some difficulties:
* What would be the format of the result in case of multiple rows, multiple columns?
* How (do we need to) to prevent no-readonly queries?

**Comment by sixcorners** [comment]
no-readonly queries? Is that like select vs update statements with no returning clause?
maybe each row could be an element in a results array?

    value = "${data.postgresql_select_statement.tables.results[0]}"
I kind of forgot what my use case was. I guess I'll close this until I have one again.
