### ISSUE TITLE
postgresql_database: DEFAULT value does not work as documented for encoding

### ISSUE THREAD

**Issue by dohoangkhiem** [terraform-providers/terraform-provider-postgresql#9]
According to https://www.terraform.io/docs/providers/postgresql/r/postgresql_database.html#encoding

> encoding - (Optional) Character set encoding to use in the database. Specify a string constant (e.g. UTF8 or SQL_ASCII), or an integer encoding number. If unset or set to an empty string the default encoding is set to UTF8. If set to DEFAULT Terraform will use the same encoding as the template database. Changing this value will force the creation of a new resource as this value can only be changed when a database is created.

However setting the encoding to DEFAULT value just causes an error

```
resource "postgresql_database" "test1" {
  provider = "postgresql.test1"
  name = "test1"
  template = "template1" # "template0"
  encoding =  "DEFAULT" # "UTF8"
  lc_collate = "DEFAULT" # "en_US.UTF-8"
  lc_ctype = "DEFAULT" # "en_US.UTF-8"
```

```
* postgresql_database.test1: Error creating database "test1": pq: DEFAULT is not a valid encoding name
```

How do we use template1 with `postgresql_database` resource with default encoding from the template?

Terraform version is 0.9.8

**Comment by sean-** [comment]
@dohoangkhiem , see if #10 fixes your issue.  Please note the comment about `lifecycle`.

**Comment by cyrilgdn** [comment]
@dohoangkhiem Without answer, I allow myself to close this issue.

Feel free to reopen it if needed after having check if it's not fixed (see previous comment).
