### ISSUE TITLE
Please release new version with latest fixes. 

### ISSUE THREAD

**Issue by zytek** [terraform-providers/terraform-provider-postgresql#98]
I kindly ask maintainers to release a new version of this provider, as we are waiting eagerly to make use of recent grant related fixes. 

Sorry to bother you via github issue but I didn't see a better way.

**Comment by cyrilgdn** [comment]
Hi @zytek ,

I'll ask for a new release today and let you know here when it's done.

**Comment by cyrilgdn** [comment]
Hi, sorry for the delay but v1.2.0 has been released last week.
